/****************************************************************
Name - Chinmay Sinha
Course - M.Sc Data and Computational Science
Module - Scientific Programming (ICHEC) (ACM40660)
College -- University College Dublin
****************************************************************/

// Write a randomarray(n, max) function that returns an array of size n integers, filled with random
// values comprised between 0 and max.


// Importing all th standard libraries
#include <stdlib.h>
#include <stdio.h>
#include <conio.h>


// defining the randomarray function

int * randomarray( int n, int max) 
	{
	
	int i;
	// allocates the requested memory (n*sizeof(int)) and returns a pointer *arr
	int *arr =  (int*)malloc(n*sizeof(int));
	
	//using srand uses an integer value  as seed by the pseudo-random number generator algorithm.
	srand(1111);
	// in other words sets the starting point for producing a series of pseudo-random integers
	
	// looping through the entire size of the array (n)
	while (i < n) {
		
		// generating random numbers using the rand() function
		arr[i] = rand() % max+1;

		i++;
	}	

	return arr;
	
}


// defining the main() fuction 
// testing the the above randomarray function

int main() 

{
	
	int size, i =0, j=0,max,*array;
	
	
	// taking the size of the array as an input
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++++");
	printf("Enter the size of the array as per your choice:");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	scanf("%d",&size);
	
	
	// Taking the maximum value as input for the random number to be generated
	// rand() < max value
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++");
	printf("Enter the maximum value for the random number to be generated:");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	scanf("%d",&max);
	
	// Callin the function defined above
	array = randomarray(size,max);
	

	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++++");
	printf("The Random Array generated is:");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n");
	
	// Printing the array generated by the randomarray function
	while (i < size) 
	{
		
		printf("\narray[%d] = %d", i, array[i]);
		printf("\n\n");
		i++;
	}
	
	printf("\n\n");
	return 0;
}



