/****************************************************************
Name - Chinmay Sinha
Course - M.Sc Data and Computational Science
Module - Scientific Programming (ICHEC) (ACM40660)
College -- University College Dublin
****************************************************************/

// importing standard libraries
#include<stdio.h>

// chopsearch(i, n, arr, amin, amax) recursive function that returns the smallest index of
// a subset of an array arr of size n, containing the value i or −1 if it’s not present.


// Defining chopsearch function
// This function assumes that the array is sorted in ascending order

int chopsearch(int i, int n, int arr[], int amin, int amax )
{
	int k;
	int x = amin + (amax - amin)/2;
		
	// the function will call itself on the ’left’ half of the array, bounded by min
	// and x (or return −1 if that half is empty)
   if (i < arr[x] ) 
	   {
		   // Checking for the empty array
		   if (amin >= x) {return -1;}
		   
		   else {return chopsearch(i,n,arr, amin, x-1);}			 
		}
	
	// the function will call itself on the ’right’ half of the array, bounded by x
	// and max (or return −1 if that half is empty)	
   if (i > arr[x] ) 
	   {
		   // Checking for the empty array
		   if (amin >= x) {return -1;}
		   
		   else {return chopsearch(i,n,arr, x+1, amax);}			 
		}
	
	
	// the function should iterate over elements ahead of x until it finds the lowest
	// array index containing the value i	
	if (i = arr[x] ) 
	{		   
		// loop through the remaining array
		for(k=x; k<=n-1; k++) 
		{
			if (arr[k] == i) return k; 
		}
	}
	
}

// defining main function
int main()
{
    int j;
	// Assuming an already sorted array - Argument 1
	int arr[] = {2, 3, 4, 5, 10, 15, 25, 40};
	
	// Taking the size of array as Argument 2
	int n = sizeof(arr)/sizeof(arr[0]);
    
	// Value to search as '3'
	
	// int x = 3;
	int x=1000;
    
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n");
	printf("\n\nFor the array \n\n");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n");
	printf("\n\n");
	
	// Printing the array generated by the randomarray function
	while (j < n) 
	{
		
		printf("%d\t", arr[j]);
		
		j++;
	}
	printf("\n\n");
	
	// Calling the above function and storing the index as 'index'
	int index = chopsearch(x, n, arr, 0, n-1);
	
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	
    if (index != -1)
       printf("Element %d is present at index %d", x, index);
    else
        printf("Element %d is not present", x);
    
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	
	
	return 0;
}


/*** Searching for i =3
++++++++++++++++++++++++++++++++++++++++++++++


For the array

++++++++++++++++++++++++++++++++++++++++++++++


2       3       4       5       10      15      25      40



++++++++++++++++++++++++++++++++++++++++++++++

Element 3 is present at index 1

++++++++++++++++++++++++++++++++++++++++++++++
***********************************************************/

/*** Searching for i=1000

++++++++++++++++++++++++++++++++++++++++++++++


For the array

++++++++++++++++++++++++++++++++++++++++++++++


2       3       4       5       10      15      25      40



++++++++++++++++++++++++++++++++++++++++++++++

Element 1000 is not present

++++++++++++++++++++++++++++++++++++++++++++++

*/

