/****************************************************************
Name - Chinmay Sinha
Course - M.Sc Data and Computational Science
Module - Scientific Programming (ICHEC) (ACM40660)
College -- University College Dublin
****************************************************************/

// Write a bubblesort(n, arr) recursive function (or subroutine) that sorts the size n array of integers
// arr in ascending order, through the process called bubble sorting. Bubble sorting consists in
// repeated passes, stepping through the list to be sorted, comparing each pair of adjacent items and
// swapping them if they are in the wrong order. The pass through the list is repeated until no swaps
// are needed, which indicates that the list is sorted.


// Importing all th standard libraries
#include <stdlib.h>
#include <stdio.h>
#include <conio.h>


// void swap(int*, int*); //bubblesort function declaration
void bubblesort(int arr[], int n);


/****************************************************************************
BUBBLE SORT FUNCTION
=================
****************************************************************************/

// Defining the recursive function bubble sort

void bubblesort(int arr[], int n)
{
	// temporary variable later used for swapping
	int t;
	
    // Base case
    if (n == 1)
        return;
 
    // Moving the largest element to other side
    for (int i=0; i<n-1; i++) 
	{
    
	// Checking for the condition if arr[i] is greater than arr[i+1]
		if (arr[i] > arr[i+1]) 
		{
			
		t = arr[i];                     //create new long variable t equal to value of arr[i]
		arr[i] = arr[i+1];           //update i index value to i + 1 value
		arr[i+1] = t;                  // Values SWAPPED
		
		}		
	}
	
    // recursive call for the remaining array
    bubblesort(arr, n-1);
}

/***************************************************************************
***************************************************************************/

// definition of the randomarray function to generate a random array

int * randomarray( int n, int max) 
	{
	
	int i;
	// allocates the requested memory (n*sizeof(int)) and returns a pointer *arr
	int *arr =  (int*)malloc(n*sizeof(int));
	
	//using srand uses an integer value  as seed by the pseudo-random number generator algorithm.
	srand(1000000000);
	// seeding the runs to get the same output
	// in other words sets the starting point for producing a series of pseudo-random integers
	
	// looping through the entire size of the array (n)
	while (i < n) {
		
		// generating random numbers using the rand() function
		arr[i] = rand() % max+1;

		i++;
	}	

	return arr;
	
}


// defining the main() fuction 
// testing the the above bubblesort function

int main() 

{
	
	int size, i =0, j=0,max,*array;
	
	
	// taking the size of the array as an input
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++++");
	printf("Enter the size of the array as per your choice:");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	scanf("%d",&size);
	
	
	// Taking the maximum value as input for the random number to be generated
	// rand() < max value
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++");
	printf("Enter the maximum value for the random number to be generated:");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	scanf("%d",&max);
	
	// Callin the function defined above
	array = randomarray(size,max);
	

	printf("\n+++++++++++++++++++++++++++++++++++++++++++++\n");
	printf("The Random Array generated is:\n");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n");
	
	// Printing the array generated by the randomarray function
	while (i < size) 
	{
		
		printf("\narray[%d] = %d", i, array[i]);
		printf("\n\n");
		i++;
	}
	
	
	//using the bubblesort function defined above
	
	bubblesort(array, size);
	
	
	printf("\n++++++++++++++++++++++++++++++++++++++++++++\n");
	printf("The Sorted Array is:\n");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n");
	
	// Printing the array generated by the randomarray function
	while (j < size) 
	{
		
		printf("\narray[%d] = %d", j, array[j]);
		printf("\n\n");
		j++;
	}
	
	return 0;
}
										/*** end of code ****/
										/*** output below ***/

/***********************************************************************
OUTPUT
=======
***********************************************************************/
/*

Case 1 : n=6 , mac = 10
===================

++++++++++++++++++++++++++++++++++++++++++++++Enter the size of the array as per your choice:++++++++++++++++++++++++++++++++++++++++++++++

6


++++++++++++++++++++++++++++++++++++++++++++Enter the maximum value for the random number to be generated:++++++++++++++++++++++++++++++++++++++++++++++

10

+++++++++++++++++++++++++++++++++++++++++++++
The Random Array generated is:
++++++++++++++++++++++++++++++++++++++++++++++

array[0] = 7


array[1] = 8


array[2] = 5


array[3] = 9


array[4] = 6


array[5] = 1


++++++++++++++++++++++++++++++++++++++++++++
The Sorted Array is:
++++++++++++++++++++++++++++++++++++++++++++++

array[0] = 1


array[1] = 5


array[2] = 6


array[3] = 7


array[4] = 8


array[5] = 9

// Same case called again
Case 2 : n=6 , max = 10
=========================

++++++Enter the size of the array as per your choice:++++++++++++++++++++++

6


++++++++++++++++++++++++++++++++++++++++++++Enter the maximum value for the random number to be generated:++++++++++++++++++++++++++++++++++++++++++++++

10

+++++++++++++++++++++++++++++++++++++++++++++
The Random Array generated is:
++++++++++++++++++++++++++++++++++++++++++++++

array[0] = 7


array[1] = 8


array[2] = 5


array[3] = 9


array[4] = 6


array[5] = 1


++++++++++++++++++++++++++++++++++++++++++++
The Sorted Array is:
++++++++++++++++++++++++++++++++++++++++++++++

array[0] = 1


array[1] = 5


array[2] = 6


array[3] = 7


array[4] = 8


array[5] = 9





















