/****************************************************************
Name - Chinmay Sinha
Course - M.Sc Data and Computational Science
Module - Scientific Programming (ICHEC) (ACM40660)
College -- University College Dublin
****************************************************************/

// importing standard libraries
#include<stdio.h>


// search(i, n, arr) function that returns the smallest index of the size n array of integers
// arr containing the value i or −1 if it’s not present.
 
/* Function to search i in array[] */
int search(int i, int n, int arr[] ) 
{
	int loop; 
	
	// Assuming that the array is sorted in ascending order
	// Scanning the list from the beginning until it finds the correct element
	for(loop=0; loop<n; loop++) {
	
	if (arr[loop] == i) return loop;

	// if an element superior to i is found then break from loop and return -1
	if  (arr[loop] > i) break;
	
	} 

// if the correct element is not found or an element superior to i is found(the array being sorted, that means the element we’re looking for is not present) or the end of the array is reached then return -1
	return -1;
} 


// defining the main() function 
// testing the the above search function

int main()
{
    // Assuming an already sorted array - Argument 1
	int arr[] = {2,3,3,4,5,5,7,8,10};
	int i=0,j=0;
    
	// Taking the size of array as Argument 2
	int n = sizeof(arr)/sizeof(arr[0]);
    
	// Value to search as '3'
	int value = 3;
    
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n");
	printf("\n\nFor the array \n\n");
	printf("++++++++++++++++++++++++++++++++++++++++++++++\n");
	printf("\n\n");
	
	// Printing the array generated by the randomarray function
	while (j < n) 
	{
		
		printf("%d\t", arr[j]);
		
		j++;
	}
	printf("\n\n");
	
	// Calling the above function and storing the index as 'index'
	int index = search(value, n, arr);
	
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	
    if (index != -1)
       printf("Element %d is present at index %d", value, index);
    else
        printf("Element %d is not present", value);
    
	printf("\n\n++++++++++++++++++++++++++++++++++++++++++++++\n\n");
	
	
	return 0;
}
/*
/********************************************************
OUTPUT
*********************************************************


++++++++++++++++++++++++++++++++++++++++++++++


For the array

++++++++++++++++++++++++++++++++++++++++++++++


2       3       3       4       5       5       7       8       10



++++++++++++++++++++++++++++++++++++++++++++++

Element 3 is present at index 1

++++++++++++++++++++++++++++++++++++++++++++++
*/